name: Generate Sitemap

on:
  schedule:
    - cron: '0 10 * * *'  # تشغيل يوميًا عند منتصف الليل UTC
  workflow_dispatch:    # يمكن تشغيله يدويًا من GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Generate sitemap.xml
        run: python generate_sitemap.py

      - name: Commit and push sitemap.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap.xml (automated)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
